package com.kito.core.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.kito.core.database.dao.AttendanceDAO
import com.kito.core.database.dao.SectionDAO
import com.kito.core.database.dao.StudentDAO
import com.kito.core.database.dao.StudentSectionDAO
import com.kito.core.database.entity.AttendanceEntity
import com.kito.core.database.entity.SectionEntity
import com.kito.core.database.entity.StudentEntity
import org.koin.core.annotation.Provided

@Provided
@Database(
    entities = [AttendanceEntity::class, StudentEntity::class, SectionEntity::class],
    version = 1,
    exportSchema = false
)
@ConstructedBy(AppDBConstructor::class)
abstract class AppDB: RoomDatabase() {
    abstract fun attendanceDao(): AttendanceDAO
    abstract fun studentDao(): StudentDAO
    abstract fun sectionDao(): SectionDAO
    abstract fun studentSectionDao(): StudentSectionDAO
}

// The actual implementation is generated by Room's KSP processor
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDBConstructor : RoomDatabaseConstructor<AppDB> {
    override fun initialize(): AppDB
}
