package com.kito.core.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.kito.core.database.dao.ActiveSessionDAO
import com.kito.core.database.dao.AttendanceDAO
import com.kito.core.database.dao.SectionDAO
import com.kito.core.database.dao.StudentDAO
import com.kito.core.database.dao.StudentSectionDAO
import com.kito.core.database.entity.ActiveSessionEntity
import com.kito.core.database.entity.AttendanceEntity
import com.kito.core.database.entity.SectionEntity
import com.kito.core.database.entity.StudentEntity
import org.koin.core.annotation.Provided
import androidx.room.migration.Migration
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.execSQL

@Provided
@Database(
    entities = [AttendanceEntity::class, StudentEntity::class, SectionEntity::class, ActiveSessionEntity::class],
    version = 2,
    exportSchema = false
)
@ConstructedBy(AppDBConstructor::class)
abstract class AppDB: RoomDatabase() {
    abstract fun attendanceDao(): AttendanceDAO
    abstract fun studentDao(): StudentDAO
    abstract fun sectionDao(): SectionDAO
    abstract fun studentSectionDao(): StudentSectionDAO
    abstract fun activeSessionDao(): ActiveSessionDAO
}

// The actual implementation is generated by Room's KSP processor
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDBConstructor : RoomDatabaseConstructor<AppDB> {
    override fun initialize(): AppDB
}

val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL("ALTER TABLE `SectionEntity` ADD COLUMN `academic_year` TEXT NOT NULL DEFAULT ''")
        connection.execSQL("ALTER TABLE `SectionEntity` ADD COLUMN `term_code` TEXT NOT NULL DEFAULT ''")
        connection.execSQL("ALTER TABLE `SectionEntity` ADD COLUMN `version` INTEGER NOT NULL DEFAULT 0")
        connection.execSQL("""
            CREATE TABLE IF NOT EXISTS `ActiveSessionEntity` (
                `id` INTEGER NOT NULL,
                `academic_year` TEXT NOT NULL,
                `term_code` TEXT NOT NULL,
                `version` INTEGER NOT NULL,
                PRIMARY KEY(`id`)
            )
        """)
    }
}
